@startuml
left to right direction

object readDocumentVerify {
  characters = "List<Character>"
  propertiesFactory = CharacterPropertiesFactory
}

object characterFactory {
  flyweights = HashMap<String, CharacterProperties>
}

object CharacterProperties2 {
  font = "Arial"
  color = "Black"
  size = 14
}
object CharacterProperties1 {
  font = "Arial"
  color = "Black"
  size = 16
}
object CharacterProperties3 {
  font = "Verdana"
  color = "Blue"
  size = 18
}
object CharacterProperties4 {
  font = "Verdana"
  color = "Red"
  size = 12
}

object CharacterProperties5 {
  font = "Calibri"
  color = "Blue"
  size = 99
}

object Character1 {
  character = 'H'
}
object Character2 {
  character = 'e'
}
object Character3 {
  character = 'l'
}
object Character4 {
  character = 'l'
}
object Character5 {
  character = 'o'
}
object Character6 {
  character = 'W'
}
object Character7 {
  character = 'o'
}
object Character8 {
  character = 'r'
}
object Character9 {
  character = 'l'
}
object Character10 {
  character = 'd'
}
object Character11 {
  character = 'C'
}
object Character12 {
  character = 'S'
}
object Character13 {
  character = '5'
}
object Character14 {
  character = '8'
}
object Character15 {
  character = '0'
}
object Character16 {
  character = '0'
}

readDocumentVerify o-- characterFactory : "uses"
characterFactory -[hidden]-> CharacterProperties1
characterFactory -[hidden]-> CharacterProperties2
characterFactory -[hidden]-> CharacterProperties3
characterFactory -[hidden]-> CharacterProperties4
characterFactory -[hidden]-> CharacterProperties5
readDocumentVerify o-- Character1 : "contains"
readDocumentVerify o-- Character2 : "contains"
readDocumentVerify o-- Character3 : "contains"
readDocumentVerify o-- Character4 : "contains"
readDocumentVerify o-- Character5 : "contains"
readDocumentVerify o-- Character6 : "contains"
readDocumentVerify o-- Character7 : "contains"
readDocumentVerify o-- Character8 : "contains"
readDocumentVerify o-- Character9 : "contains"
readDocumentVerify o-- Character10 : "contains"
readDocumentVerify o-- Character11 : "contains"
readDocumentVerify o-- Character12 : "contains"
readDocumentVerify o-- Character13 : "contains"
readDocumentVerify o-- Character14 : "contains"
readDocumentVerify o-- Character15 : "contains"
readDocumentVerify o-- Character16 : "contains"

characterFactory *-- CharacterProperties2 : "manages"
characterFactory *-- CharacterProperties1 : "manages"
characterFactory *-- CharacterProperties3 : "manages"
characterFactory *-- CharacterProperties4 : "manages"
characterFactory *-- CharacterProperties5 : "manages"

Character1 *-- CharacterProperties5 : "uses"
Character2 *-- CharacterProperties2 : "uses"
Character3 *-- CharacterProperties2 : "uses"
Character4 *-- CharacterProperties2 : "uses"
Character5 *-- CharacterProperties2 : "uses"
Character6 *-- CharacterProperties5 : "uses"
Character7 *-- CharacterProperties2 : "uses"
Character8 *-- CharacterProperties2 : "uses"
Character9 *-- CharacterProperties2 : "uses"
Character10 *-- CharacterProperties2 : "uses"
Character11 *-- CharacterProperties3 : "uses"
Character12 *-- CharacterProperties3 : "uses"
Character13 *-- CharacterProperties4 : "uses"
Character14 *-- CharacterProperties4 : "uses"
Character15 *-- CharacterProperties4 : "uses"
Character16 *-- CharacterProperties4 : "uses"

@enduml
